// =============================================================================
// PI-1 / D — "no AI residue" production sweep (source invariant).
// =============================================================================
//
// Asserts that CUSTOMER-FACING and ADMIN-facing component sources do not carry
// the specific wording that would imply the product is AI-generated, a demo,
// unfinished, or a development prototype. The banned substrings below are
// deliberately specific enough to avoid matching the legitimate `placeholder=`
// HTML attribute, developer comments, or the factual OCR disclosure in
// PrivacyView (Google Gemini is the REAL, disclosed OCR service).
//
// LIMITATION (documented, per the directive): this is a source-text scan, not a
// browser render. It can prove the wording does not exist in the shipped
// strings; it cannot prove a runtime interpolation never contains it. The
// stronger runtime guard for notification categories is
// containsForbiddenCustomerTerm() in config/customerNotifications.ts.
// =============================================================================
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';

const CUSTOMER_FACING = [
  'src/components/HomeView.tsx',
  'src/components/OwnerView.tsx',
  'src/components/FinderView.tsx',
  'src/components/PublicItemView.tsx',
  'src/components/CustomerDashboard.tsx',
  'src/components/CustomerAccountView.tsx',
  'src/components/CustomerActivationView.tsx',
  'src/components/ReportLostView.tsx',
  'src/components/SignInView.tsx',
  'src/components/BecomeAgentView.tsx',
  'src/components/AgentActivationView.tsx',
  'src/components/AgentView.tsx',
  'src/components/customer/LostReportWizard.tsx',
  'src/components/customer/LostReportsSection.tsx',
  'src/components/customer/PossibleMatches.tsx',
  'src/components/customer/NotificationCentre.tsx',
  'src/components/admin/claims/ClaimsAdministration.tsx',
  'src/components/admin/claims/ClaimDetailPanel.tsx',
  'src/components/admin/lostReports/LostReportsAdministration.tsx',
];

const BANNED = [
  'generated by ai',
  'ai-generated',
  'ai-powered',
  'ai assistant',
  'artificial intelligence',
  'chatgpt',
  'gpt-',
  'claude',
  'copilot',
  'lorem ipsum',
  'coming soon',
  'under construction',
  'demo credentials',
  'placeholder text',
  'fake data',
  'sample data',
  'mock data',
  'test user',
  'dummy data',
  'this is a demo',
];

const read = (rel: string) =>
  readFileSync(new URL('../..' + '/' + rel, import.meta.url), 'utf8');

describe('PI-1 D — no AI/demo residue in shipped surfaces', () => {
  it('no customer/operator-facing component carries AI/demo/unfinished wording', () => {
    for (const rel of CUSTOMER_FACING) {
      const source = read(rel).toLowerCase();
      for (const word of BANNED) {
        expect(source, `${rel} contains banned residue "${word}"`).not.toContain(word);
      }
    }
  });

  it('PrivacyView discloses the real OCR service (legitimate, not residue)', () => {
    const source = read('src/components/PrivacyView.tsx').toLowerCase();
    // The factual third-party-processor disclosure must remain.
    expect(source).toContain('google gemini');
  });
});